--
-- DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
--
-- Program: Blood Altar LUA
--
-- Description: Automatize Blood Magic's Altar with ComputerCraft/CC:Tweaked.
--
-- Author: Scheigy
--
-- Source: https://github.com/iammael/BloodAltarLUA
--
--
local LIP = require 'LIP'
local CONFIG = LIP.load("config.ini")

local mon = peripheral.find("monitor")
local inputChest = peripheral.wrap("minecraft:chest_0")
local outputChest = peripheral.wrap("minecraft:chest_1")
local altar = peripheral.wrap("entangled:tile_1")

--
local RECIPES = {}

--
local CURRENT_LOG_ON_MONITOR = 0
local TOTAL_CRAFTS_SESSION = 0

-- DYNAMIC RECIPES

function createRecipes()
    local recipesData = LIP.load("recipes.ini")
    local i = 0

    for index, recipe in pairs(recipesData) do
        i = i + 1
        -- print(index, recipe.name)
        RECIPES[i] = {
            name = recipe.name,
            displayName = recipe.displayName,
            cost = recipe.cost
        }
    end

    printDebug("Loaded " .. i .. " recipes.")
end

-- END DYNAMIC RECIPES

-- CONFIG

function updateConfig()
    CONFIG.Program.TOTAL_CRAFTS = CONFIG.Program.TOTAL_CRAFTS + TOTAL_CRAFTS_SESSION
    LIP.save("config.ini", CONFIG)
end

-- MONITOR

function logOnMonitor(msg, type)
    print("[MON] " .. msg)

    -- Erase log if screen too full
    if (CURRENT_LOG_ON_MONITOR == CONFIG.Program.MAX_LOG_ON_MONITOR) then
        initMonitor()
        CURRENT_LOG_ON_MONITOR = 0
    end

    -- Change color base on message type
    if (type == "warning") then
        mon.setTextColor(colors.orange)
    elseif (type == "error") then
        mon.setTextColor(colors.red)
    elseif (type == "success") then
        mon.setTextColor(colors.green)
    else
        mon.setTextColor(colors.black)
    end

    local cursorPosY = 5 + CURRENT_LOG_ON_MONITOR
    mon.setCursorPos(2, cursorPosY)
    mon.write(msg)
    CURRENT_LOG_ON_MONITOR = CURRENT_LOG_ON_MONITOR + 1
end

-- Footer
function writeFooterOnMonitor()
    mon.setTextColor(colors.black)
    mon.setCursorPos(40, 18)
    mon.write("Total:")
    mon.setCursorPos(40, 19)
    mon.write(CONFIG.Program.TOTAL_CRAFTS .. " crafts.")
end

function initMonitor()
    mon.setBackgroundColor(colors.white)
    mon.clear()
    mon.setTextColor(colors.black)
    mon.setTextScale(1.3)

    -- Title
    mon.setCursorPos(18, 1)
    mon.setTextColor(colors.red)
    mon.write("BloodAltar")
    mon.setTextColor(colors.green)
    mon.write("LUA")

    -- Log Header
    mon.setTextColor(colors.black)
    mon.setCursorPos(2, 3)
    mon.write("Log:")

    writeFooterOnMonitor()
end

-- CRAFT

function tryCrafting()
    local listInputChest = inputChest.list()
    local totalSlatesCrafted = 0

    if (#listInputChest == 0) then
        return -1
    else
        for x = 1, #listInputChest do
            local craftTable = {
                name = listInputChest[x].name,
                count = listInputChest[x].count,
                slot = x
            }

            if (checkTankCapacityRequirements() == false) then
                return 0
            else
                for y = 1, craftTable.count do
                    if (craft(craftTable) == -1) then
                        return -2
                    end
                    totalSlatesCrafted = totalSlatesCrafted + 1
                end
            end
        end
    end

    TOTAL_CRAFTS_SESSION = TOTAL_CRAFTS_SESSION + totalSlatesCrafted
    return totalSlatesCrafted
end

function craft(craftTable)
    inputChest.pushItems(peripheral.getName(altar), craftTable.slot, 1)
    if (waitUntilSlateTransforms(craftTable.name) == -1) then
        return -1
    else
        outputChest.pullItems(peripheral.getName(altar), 1)
    end
    return 0
end

function waitUntilSlateTransforms(originalSlateName)
    local i = 0

    -- Printing current craft on monitor
    for x = 1, #RECIPES do
        if (string.find(RECIPES[x].name, originalSlateName) ~= nil) then
            logOnMonitor("Infusing 1 " .. RECIPES[x].displayName .. "...")
        end
    end

    while i < CONFIG.Program.TIMEOUT do
        local slateInAltar = altar.list()[1]
        if (slateInAltar.name == originalSlateName) then
            sleep(1)
            i = i + 1
        else
            return 0
        end
    end
    return -1
end

function checkTankCapacityRequirements()
    local currentLifeEssence = altar.tanks()[1].amount

    if (currentLifeEssence >= CONFIG.Altar.LIFE_ESSENCE_REQUIRED_MIN) then
        return true
    end
    return false
end

-- MISC FUNC

function printDebug(msg)
    if CONFIG.Program.DEBUG == true then
        print(msg)
    end
end

--

function init()
    term.clear()

    createRecipes()
    initMonitor()
end

function main()
    init()

    while true do
        ret = tryCrafting()

        if ret == -1 then -- Nothing is found in the input chest
            logOnMonitor("Nothing to do.")
            sleep(15)
        elseif ret == -2 then -- The crafting happened for too long
            logOnMonitor("CONFIG.Program.TIMEOUT (" .. CONFIG.Program.TIMEOUT .. " seconds).", "error")
            sleep(10)
        elseif ret == 0 then -- The altar tank doesn't meet the minimum requirement for the craft
            logOnMonitor("Tank capacity is < " .. CONFIG.Altar.LIFE_ESSENCE_REQUIRED_MIN .. ".", "warning")
            sleep(3)
        else
            updateConfig()
            logOnMonitor("Successfully crafted " .. ret .. " recipe(s).", "success")
            writeFooterOnMonitor()
            sleep(1)
        end
    end
end

main()
